FROM openjdk:8
MAINTAINER  Author Name <israj.haliri@gmail.com>
ADD target/app-config-0.0.1-SNAPSHOT.jar /tmp/app-config-0.0.1-SNAPSHOT.jar
EXPOSE 10000
ENTRYPOINT ["java", "-jar", "/tmp/app-config-0.0.1-SNAPSHOT.jar"]
